# Generated by Django 3.0.4 on 2020-04-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0002_auto_20200403_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_map.Province'),
            preserve_default=False,
        ),
    ]
