# Generated by Django 3.0.4 on 2020-04-10 15:28

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0003_district_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='location',
            field=djgeojson.fields.PointField(),
        ),
    ]
