# Generated by Django 3.0.4 on 2020-04-14 04:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0004_auto_20200410_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
