# Generated by Django 3.0.4 on 2020-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0005_auto_20200414_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
