# Generated by Django 3.0.4 on 2020-04-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0006_auto_20200423_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
