# Generated by Django 3.0.4 on 2020-04-26 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0007_auto_20200423_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='poly',
            new_name='geom',
        ),
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.AddField(
            model_name='district',
            name='cc_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='engtype_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='gid_0',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='gid_1',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='gid_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='hasc_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='name_0',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='name_1',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='name_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='nl_name_1',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='nl_name_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='type_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='varname_2',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
