# Generated by Django 3.0.4 on 2020-04-26 15:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0010_auto_20200426_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(blank=True, max_length=2048, null=True)),
                ('name_0', models.CharField(blank=True, max_length=2048, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
