# Generated by Django 3.0.4 on 2020-04-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0012_auto_20200426_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='related_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem_map.Province'),
        ),
        migrations.AddField(
            model_name='province',
            name='related_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem_map.Country'),
        ),
    ]
