# Generated by Django 3.0.4 on 2020-04-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0013_auto_20200426_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='related_district',
            field=models.ForeignKey(default=935, on_delete=django.db.models.deletion.CASCADE, to='problem_map.District'),
            preserve_default=False,
        ),
    ]
