# Generated by Django 3.0.4 on 2020-05-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0016_problemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='related_problem_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_map.ProblemType'),
            preserve_default=False,
        ),
    ]
