# Generated by Django 3.0.4 on 2020-05-06 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0018_remove_problem_thematic_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='occurrence_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
