# Generated by Django 3.0.4 on 2020-05-28 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0019_problem_occurrence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicfield',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
