# Generated by Django 3.0.4 on 2020-09-24 23:17

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0020_thematicfield_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Ülke', 'verbose_name_plural': 'Ülkeler'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kişi', 'verbose_name_plural': 'Kişiler'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problemler'},
        ),
        migrations.AlterModelOptions(
            name='problemtype',
            options={'verbose_name': 'Problem Çeşidi', 'verbose_name_plural': 'Problem Çeşitleri'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'İl', 'verbose_name_plural': 'İller'},
        ),
        migrations.AlterModelOptions(
            name='thematicfield',
            options={'verbose_name': 'Tematik Alan', 'verbose_name_plural': 'Tematik Alanlar'},
        ),
        migrations.AlterField(
            model_name='person',
            name='could_contact',
            field=models.BooleanField(verbose_name='İletişim İzni'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta Adresi'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=1024, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=1024, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon No'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onay'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Problem Tanımı'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='occurrence_date',
            field=models.DateField(verbose_name='Gerçekleşme Tarihi'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='related_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_map.District', verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='related_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem_map.Person', verbose_name='İlgili Kişi'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='related_problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_map.ProblemType', verbose_name='İlgili Problem Çeşidi'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onay'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='name',
            field=models.TextField(verbose_name='Problem Çeşidi Tanımı'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='thematic_field',
            field=models.ManyToManyField(to='problem_map.ThematicField', verbose_name='Tematik Alan'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='thematicfield',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='thematicfield',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Tematik Alan İsmi'),
        ),
    ]
