# Generated by Django 3.0.4 on 2020-10-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_map', '0022_auto_20200929_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='İsim'),
        ),
    ]
